apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-kinetic
  labels:
    app: ubuntu-kinetic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-kinetic
  template:
    metadata:
      labels:
        app: ubuntu-kinetic
    spec:
      containers:
      - name: ubuntu-kinetic
        image: ubuntu:kinetic
        # Just spin &amp; wait forever
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        ports:
        - containerPort: 80
        volumeMounts:
        - name: ubuntu-persistent-storage
          mountPath: /home
      volumes:
      - name: ubuntu-persistent-storage
        persistentVolumeClaim:
          claimName: ubuntu-pv-claim